# This file was generated by nvfetcher, please do not modify it manually.
{
  fetchgit,
  fetchurl,
  fetchFromGitHub,
  dockerTools,
}:
{
  wechat-web-devtools-linux = {
    pname = "wechat-web-devtools-linux";
    version = "v2.01.2510290-2";
    src = fetchTarball {
      url = "https://github.com/msojocs/wechat-web-devtools-linux/releases/download/v2.01.2510290-2/WeChat_Dev_Tools_v2.01.2510290-2_x86_64_linux.tar.gz";
      sha256 = "sha256-Y6XOcIBwGhXHpjwbknmQnVIGAswalJKohxf8/+53298=";
    };
  };
}
